config/routes.rb
Personal::Application.routes.draw do

  match '/about', :to => "pages#about"
  match '/privacy', :to => "pages#privacy"
  match '/terms', :to => "pages#terms"
  match '/team', :to => "pages#team"


  match '*path' => redirect('/')
  match '/home' => redirect('/')
  root :to => "pages#home"











end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   def index
    response.headers['Cache-Control'] = 'public, max-age=600'
    render :text => "Rendered at #{Time.now}"
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

  def privacy
    @title = "Privacy"
  end

  def terms
    @title = "Terms of use"
  end

  def faq
    @title = "FAQ"
  end

  def team
    @title = "Meet the Team"
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_analytics_js
    '<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push([\'_setAccount\', \'UA-24818194-1\']);
  _gaq.push([\'_trackPageview\']);

  (function() {
    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;
    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';
    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>'
  end

  def title
    base_title = "Apps for Action"
    @title.nil? ? base_title : "#{base_title} | #{@title}"
  end

  def clicky
    '<script src="http://static.getclicky.com/js" type="text/javascript"></script>
    <script type="text/javascript">try{ clicky.init(66457842); }catch(err){}</script>'
  end

 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div></div>
<footer style="font-size:150%; font-family:Arial,Helvetica,sans-serif;">
        <%= link_to "Home", home_path %> &middot; 
        <%= link_to "About", about_path %> &middot;
        <%= link_to "Team", team_path %> &middot;

<a href="http://apps4action.wufoo.com/forms/z7x3k7/" onclick="window.open(this.href,  null, 'height=320, width=680, toolbar=0, location=0, status=1, scrollbars=1, resizable=1'); return false">Add a Charity &middot;</a>

<a href="http://AppsforAction.Wordpress.com/">Blog</a> <!-- &middot; -->      
        <br/>

<a style="font-size:80%" href="http://apps4action.wufoo.com/forms/m7x3w7/" onclick="window.open(this.href,  null, 'height=320, width=680, toolbar=0, location=0, status=1, scrollbars=1, resizable=1'); return false">Contact Us</a> &middot;

        <a style="font-size:80%;" <%= link_to "Privacy", privacy_path %> &middot; </a>
       
        <a style="font-size:80%;" <%= link_to "Terms", terms_path %> </a>

        <%#<%= link_to "FAQ", faq_path%>
        
        

<h2 style="font-size:50%; line-height: 75%">&copy;Apps for Action 2011-2012. All rights reserved.</h2>

<!-- <a href="http://AppsforAction.Wordpress.com/" onclick="window.open(this.href,  null, 'height=850, width=835, toolbar=0, location=0, status=1, scrollbars=1, resizable=1'); return false">Blog</a> &middot; -->

</footer>

app/views/layouts/_header.html.erb
<header>
</header>

app/views/layouts/_stylesheets.html.erb
      <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
      <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
      <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
      <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
      <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/pages/about.html.erb
<html>
<head>
<style type="text/css">
body
{
	    background-repeat: no-repeat;
background-color:#FFFFFF;
background-image: -webkit-gradient(linear, left top, left bottom, from(#40930F), to(#FFFFFF)) fixed; /* Saf4+, Chrome */
  background-image: -webkit-linear-gradient(top, #40930F, #FFFFFF); /* Chrome 10+, Saf5.1+, iOS 5+ */
  background-image:    -moz-linear-gradient(top, #40930F, #FFFFFF); /* FF3.6 */
  background-image:     -ms-linear-gradient(top, #40930F, #FFFFFF); /* IE10 */
  background-image:      -o-linear-gradient(top, #40930F, #FFFFFF); /* Opera 11.10+ */
  background-image:         linear-gradient(to bottom, #40930F, #FFFFFF);
  overflow:hidden
}
p.sansserif{font-family:Arial,Helvetica,sans-serif;}
</style>
</head>

<body>
	
<center>
<div style="float: center; clear: center;">

    <div id="home_logo"><%= link_to image_tag("Apps_for_Action.png", size: "469x90"),  home_path %></div>
    
</div>
</center>

<div id="outerDiv" style="position: relative; left:0px; border: 2px solid green; width: auto; length: auto; float: left; clear: left; margin-bottom: 0em; margin-left: 0em; border-radius:10px; -moz-border-radius:10px;-moz-box-shadow: 5px 5px 2.5px #77AA55; /* Firefox 3.6 and earlier */
box-shadow: 5px 5px 2.5px #77AA55;">

<div id="semiTransparentDiv" style="position: absolute; background-color: white; filter:alpha(opacity=75);-moz-opacity:.75;opacity:.75; height: 100%; width: 100%; z-index: 1;-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;"></div>

<div id="contentDiv" style="position: relative; z-index: 2; padding: 10px; color: black; text-align:left; font-size:100%; font-family: Arial, Helvetica, sans-serif; line-height:125%"><h1 class="serif" style="font-size:300%;font-weight:bold;color:#40930F; text-decoration:underline;line-height:75%">About Us</h1>

<p style="font-size:125%;color:808080; text-align: justify;line-height: 125%"><b>Apps for Action</b> is an app recommendation engine that allows users to find new free apps that fit their interests and raise money for their favorite charities each time they download one. By using Apps for Action, the simple act of downloading a new free app turns into a real-world positive impact. Our mission is to help users connect to the apps they want, while raising money for the charities they support. </p>

</body>
</html>

<h2 style="font-size: 200%; font-family: Arial, Helvetica, sans-serif; color:#40930F; font-weight: bold;">How It Works</h2>
<ol style="margin-left:1em; line-height:125%">
	<li style="font-size: 125%;">You download a personally recommended free app, and open it on your phone.</li>
	<br />
	<li style="font-size: 125%;">App developers pay us when you try out their free app.</li>
	<br>
	<li style="font-size: 125%; font-weight:bold">We donate 25 cents to your favorite charity.</li>
</ol></style>

</div>

app/views/pages/faq.html.erb
<h1>FAQ</h1>
<b>Q: Why did you create Apps for Action?</b><br/>
Put answer here.<br/>
<b>Q: How do I ask a question?</b><br/>
A: Send an e-mail to the address listed at the bottom of this page.<br/>

app/views/pages/home.html.erb
<html>
<head> 
<!-- The following are facebook opengraph tags: -->

<meta property="og:type" content="website" />
<meta property="og:title" content="Apps for Action" />
<meta property="og:url" content="http://www.appsforaction.com" />
<meta property="og:image" content="http://www.appsforaction.com/fbicon.jpg" />

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30242628-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<div id="main_left" class="span-8" style="left:-30px; position: relative">
<center>
<span style="margin-top: -20px; float:left;">
<script>
  $(function() {
    $('#slideshow').crossSlide({
      sleep: 2,
      fade: 1
    }, [
      { <%= image_tag("Screenshot.png", :size=>"315x551")%> },
      { <%= image_tag("Screenshot2.png", :size=>"315x551")%> },
      { <%= image_tag("Screenshot3.png", :size=>"315x551")%> },
      { <img src: '../../../public/images/screenshot.png' /> }
    ])
  });
</script>	

	
<%= image_tag("Phone.png", :size=>"315x659")%>
</span>
</center>
</div>

<div id="main_right" class="span-11 last">
  
    <div style="float:top; margin-top: 0em; margin-right: 9em;" id="home_logo"><%= link_to image_tag("Apps_for_Action.png", :size=>"515x99"),  home_path %></div>

<!-- This controls the style, font, and bacground color of the call-to-action text. -->
<!-- <div id="outerDiv" style="position: relative; left:70px; border: 0px solid green; width: 500px; height: 450px; float: right; clear: right; margin-bottom: 2em; margin-left: 2em"> -->

<div id="outerDiv" style="position: relative; left:90px; border: 2px solid green; width: 515px; height: 380px; float: right; clear: right; margin-bottom: 2em; margin-left: 2em; border-radius:10px; -moz-border-radius:10px;-moz-box-shadow: 5px 5px 2.5px #77AA55; /* Firefox 3.6 and earlier */
box-shadow: 5px 5px 2.5px #66AA44;">

<div id="semiTransparentDiv" style="position: absolute; background-color: white; filter:alpha(opacity=75);-moz-opacity:.75;opacity:.75; height: 100%; width: 100%; z-index: 1;-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;"></div>

<div id="contentDiv" style="position: relative; z-index: 2; padding: 10px; color: black; text-align:left; font-size:120%; font-family: Arial, Helvetica, sans-serif; line-height:125%">Want cool new <b>free apps</b> on your Android phone? <br /> <br /> Our app recommends free apps that you would like. Each time you download a free app, <b>25 cents is donated</b> to your favorite charity. <br /> <br /> That’s right! You find the free apps you want <i><b>and</b></i> support the causes you care about. <br /> <br /> <b style="position:relative; left: 130px">What are you waiting for?</b></style>
	
	<br />
	
<!-- 	<div id='app561' class='appbrain-app'><a href='http://www.appbrain.com/app/google-maps/com.google.android.apps.maps' style='font-size: 11px; color: #555; font-family: Arial, sans-serif;'>Google Maps for Android on AppBrain</a></div><script type='text/javascript' language='javascript' src='http://www.appbrain.com/api/api.nocache.js'></script> -->
	
	   <div style="position:relative; clear:left; margin-top: 5px; margin-right: 2em; left: 110px" id="Market"><%= link_to image_tag("Play.png", :size=>"172x60"), 'https://play.google.com/store/apps/details?id=com.appsforaction&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5hcHBzZm9yYWN0aW9uIl0.' %>

<div style="position:relative; margin-top: -66px; left: 180px;" id="chart"><%= link_to image_tag("chart.png", :size=>"60x60"), 'https://play.google.com/store/apps/details?id=com.appsforaction&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5hcHBzZm9yYWN0aW9uIl0.' %>
<br />
<i style="position:absolute; left: -230px; top: 80px">Download our free app now in the Android Market</i>
</div>
<b style="position:relative; top: 50px; left: 225px">Follow Us:</b>
 <div style="position:relative; clear:left; margin-top: 25px; margin-right: 2em; left: 310px" id="fbfollow"><%= link_to image_tag("flogo.png", :size=>"30x30"), 'http://www.facebook.com/appsforaction' %></div>
  <div style="position:relative; clear:left; margin-top: -35px; margin-right: 2em; left: 347px" id="tfollow"><%= link_to image_tag("twitter.png", :size=>"31x31"), 'http://www.twitter.com/appsforaction' %></div>
</div>
</div>
</div>

  <br />


<div style="float: left;; margin-top: -15px;">        <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
              <fb:like></fb:like></div>
<div style="float: left; position:relative; left: 0px; top: 5px; "><a href="http://twitter.com/share" class="twitter-share-button" data-url="www.appsforaction.com" data-text="Check out this app!" data-count="horizontal" data-via="appsforaction">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>
</html>

app/views/pages/privacy.html.erb
<html>
<head>
<style type="text/css">
body
{
	    background-repeat: no-repeat;
background-color:#40930F;
background-image: -webkit-gradient(linear, left top, left bottom, from(#40930F), to(#FFFFFF)) fixed; /* Saf4+, Chrome */
  background-image: -webkit-linear-gradient(top, #40930F, #FFFFFF); /* Chrome 10+, Saf5.1+, iOS 5+ */
  background-image:    -moz-linear-gradient(top, #40930F, #FFFFFF); /* FF3.6 */
  background-image:     -ms-linear-gradient(top, #40930F, #FFFFFF); /* IE10 */
  background-image:      -o-linear-gradient(top, #40930F, #FFFFFF); /* Opera 11.10+ */
  background-image:         linear-gradient(to bottom, #40930F, #FFFFFF);
</style>
</head>

<body>

<center>
<div style="float: center; clear: center; margin-right: 0px; margin-bottom: 0px">

    <div id="home_logo"><%= link_to image_tag("Apps_for_Action.png", size: "469x90"),  home_path %></div>
   
</div>
</center>

<div id="outerDiv" style="position: relative; left:0px; border: 2px solid green; width: auto; length: 2000px; float: left; clear: left; margin-bottom: 0em; margin-left: 0em; border-radius:10px; -moz-border-radius:10px;-moz-box-shadow: 5px 5px 2.5px #669900; /* Firefox 3.6 and earlier */
box-shadow: 5px 5px 2.5px #669900;">

<div id="semiTransparentDiv" style="position: absolute; background-color: white; filter:alpha(opacity=75);-moz-opacity:..75;opacity:.75; height: 100%; width: 100%; z-index: 1;-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;"></div>


<div id="contentDiv" style="position: relative; z-index: 2; padding: 10px; color: black; text-align:left; font-size:120%; font-family: Arial, Helvetica, sans-serif; line-height:125%"><p style="font-size:125%;color:808080; text-align: justify;">
<h2 style="font-size: 200%; font-family: Arial, Helvetica, sans-serif; ">

<h1 style="font-size:150%;font-weight:bold;color:#40930F; text-decoration: underline; float: top; clear:right; line-height:50%; top:5px;">Privacy Policy</h1>

<h3 style="float:left; clear:left; font-size:100%">Your privacy is of the upmost importance to us.</h3>
<br />
<p style="float:left; clear:left;">At Apps for Action, we have a few fundamental principles:</p>

<ul style="float:left; clear:left;">
  <li>We don’t ask you for personal information we don’t need.</li>
  <li>We don’t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
  <li>We don’t store personal information on our servers unless required for the ongoing operation of one of our services.</li>
</ul>
<p style="font-size:100%; float:left; clear:left;">Below is our privacy policy which incorporates these goals. If you have any questions, please <a style="color:#000080" href="mailto:info@appsforaction.com">contact the Apps for Action Team</a>. Apps for Action, LLC (hereafter “Apps for Action”) operates <a style="color:#000080" href="http://appsforaction.com">appsforaction.com</a>.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Website Visitors</h2>
<p style="font-size:90%; float:left; clear:left;">Like most website operators, Apps for Action collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Apps for Action’s purpose in collecting non-personally-identifying information is to better understand how Apps for Action’s visitors use its website. From time to time, Apps for Action may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the website's usage.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Gathering of Personally-Identifying Information</h2>
<p style="font-size:100%; float:left; clear:left;">Apps for Action collects potentially personally-identifying information like Internet Protocol (IP) addresses for users. Apps for Action collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with Apps for Action. Apps for Action does not disclose personally-identifying information other than as described below.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Aggregated Statistics</h2>
<p style="font-size:100%; float:left; clear:left;">Apps for Action may collect statistics about the behavior of visitors to its websites. For instance, Apps for Action may monitor the most popular causes to which our users donate. Apps for Action may display this information publicly or provide it to others. However, Apps for Action does not disclose personally-identifying information other than as described below.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Protection of Certain Personally-Identifying Information</h2>
<p style="font-size:100%; float:left; clear:left;">Apps for Action discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Apps for Action’s behalf or to provide services available at <a style="color:#000080" href="http://appsforaction.com">appsforaction.com</a>, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using <a style="color:#000080" href="http://appsforaction.com">appsforaction.com</a>, you consent to the transfer of such information to them. Apps for Action will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Apps for Action discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when Apps for Action believes in good faith that disclosure is reasonably necessary to protect the property or rights of Apps for Action, third parties or the public at large. Apps for Action takes all measures reasonably necessary to protect against the unauthorized access, use, alteration, or destruction of potentially personally-identifying and personally-identifying information.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Cookies</h2>
<p style="font-size:100%; float:left; clear:left;">A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. As of 1 July 2011, Apps for Action does not use cookies. However, ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Apps for Action and does not cover the use of cookies by any advertisers. Apps for Action visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using <a style="color:#000080" href="http://appsforaction.com">appsforaction.com</a>.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Business Transfers</h2>
<p style="font-size:100%; float:left; clear:left;">If Apps for Action, or substantially all of its assets were acquired, or in the event that Apps for Action goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Apps for Action may continue to use your personal information as set forth in this policy.</p>
<h2 style="font-size:110%;line-height:50%; float:left; clear:left;">Privacy Policy Changes</h2>
<p style="font-size:100%; float:left; clear:left;">Although most changes are likely to be minor, Apps for Action may change its Privacy Policy from time to time, and in Apps for Action’s sole discretion. Apps for Action encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>
<div id="note" style="float:left; clear:left;">
  Apps for Action sincerely thanks <!-- <a style="color:#000080" href="http://automattic.com/privacy/"> -->http://automattic.com/privacy/</a> for releasing an open source privacy policy on which our privacy policy is based. Note: Our privacy policy is also available under a Creative Commons Sharealike license.

</style>

</body>
</p>
</div>

</body>
</html>
</div>

app/views/pages/team.html.erb
<html>
<head>
<style type="text/css">
body
{
	    background-repeat: no-repeat;
background-color:#40930F;
background-image: -webkit-gradient(linear, left top, left bottom, from(#40930F), to(#FFFFFF)) fixed; /* Saf4+, Chrome */
  background-image: -webkit-linear-gradient(top, #40930F, #FFFFFF); /* Chrome 10+, Saf5.1+, iOS 5+ */
  background-image:    -moz-linear-gradient(top, #40930F, #FFFFFF); /* FF3.6 */
  background-image:     -ms-linear-gradient(top, #40930F, #FFFFFF); /* IE10 */
  background-image:      -o-linear-gradient(top, #40930F, #FFFFFF); /* Opera 11.10+ */
  background-image:         linear-gradient(to bottom, #40930F, #FFFFFF);

}
p.sansserif{font-family:Arial,Helvetica,sans-serif;}
</style>
</head>

<body>
	
<center>
<div style="float: center; clear: center;">

    <div id="home_logo"><%= link_to image_tag("Apps_for_Action.png", size: "469x90"),  home_path %></div>
    
</div>
</center>

<div id="outerDiv" style="position: relative; left:0px; border: 2px solid green; width: auto; length: auto; float: left; clear: left; margin-bottom: 0em; margin-left: 0em; border-radius:10px; -moz-border-radius:10px;-moz-box-shadow: 5px 5px 2.5px #77AA55; /* Firefox 3.6 and earlier */
box-shadow: 5px 5px 2.5px #77AA55;">

<div id="semiTransparentDiv" style="position: absolute; background-color: white; filter:alpha(opacity=75);-moz-opacity:.75;opacity:.75; height: 100%; width: 100%; z-index: 1;-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;"></div>

<div id="contentDiv" style="position: relative; z-index: 2; padding: 10px; color: black; text-align:left; font-size:100%; font-family: Arial, Helvetica, sans-serif; line-height:125%"><h1 class="serif" style="font-size:300%;font-weight:bold;color:#40930F; text-decoration:underline;line-height:75%">Our Team</h1>


</body>
</html>

<br />


<div id="Cuy_Box" class="span-4">
<span style="margin-left: 0em; z-index: 1">
<%= image_tag "Cuy_pp2.jpg", :size=>"150x150"%></div>
<p style="/*Font-weight: bold*/; font-size: 160%; line-height: 10%"><b style="font-size: 100%;">Cuy Sheffield</b>, <i>Chief Executive Officer</i></p>

<div id="Cuy_Text" style="text-align: justify;">
<p style="font-size: 115%" float: left;>Cuy is a junior at Pomona College in Claremont, California, studying sociology. He claims to have figured out <a href="http://entrepreneurshiprockpaperscissors.wordpress.com/2012/02/27/how-to-win-rock-paper-scissors/"> how to beat a high percentage of opponents at rock paper scissors</a>. Cuy takes his pickup basketball career very seriously and is a fan of mediocre NBA role players from the late 90's.</p></div>
	
</span>

<br />
<br />
<br />

<div id="Ravi_Box" class="span-4">
<span style="margin-left: 0em;">
<%= image_tag "Ravi_pp2.jpg", :size=>"150x150"%></div>
<p style="; font-size: 160%; line-height: 10%"><b>Ravi Reddy</b>, <i>Chief Marketing Officer</i></p>

<div id="Ravi_Text" style="text-align: justify;">
<p style="font-size: 115%" float: left;>Ravi is a junior sociology major at Pomona College. He is known for being an avid bodybuilder who eats 18 eggs each morning and popularizing peanut butter-covered chicken as a dining hall staple for fellow weightlifters. Ravi is a talented impressionist of Bush, Clinton, Obama, Arnold Schwarzenegger, and many others. He also enjoys having spontaneous conversations with people about completely random topics.</p></div>
	
</span>

<br />
<br />

<div id="Mike_Box" class="span-4">
<span style="margin-left: 0em;">
<%= image_tag "Mike_pp2.jpg", :size=>"150x150"%></div>
<p style="font-size: 160%; line-height: 10%"><b>Mike Moyer</b>, <i>Chief Operating Officer</i></p>

<div id="Mike_Text" style="text-align: justify;">
<p style="font-size: 115%" float: left;>Mike is a junior economics major at Pomona College. He was nicknamed “MoneyMike” thanks to his sharpshooting left-handed jump shot in high school basketball, and the name has stuck with him. He is known for riding a homemade "<a href="http://i213.photobucket.com/albums/cc275/brooklynmachineworks/ScraperBike.jpg">scraper bike</a>" around campus.  Mike is also especially proud to unofficially lead the school in the made-up stat ‘GPA per hour spent on homework.’</p></div>
	
</span>

<br />
<br />

<div id="Eugene_Box" class="span-4">
<span style="margin-left: 0em;">
<%= image_tag "Eugene_pp2.jpg", :size=>"150x150"%></div>
<p style="font-size: 160%; line-height: 10%"><b>Eugene Aarons-Cooke</b>, <i>Chief Technology Officer</i></p>

<div id="Eugene_Text" style="text-align: justify;">
<p style="font-size: 115%" float: left;>Eugene is a junior economics major at Pomona College. He likely spends more time on the computer than he should, but if Wikipedia were down for the day and you needed an answer, he would be your best bet. Eugene is a talented photographer and avid technology buff, but wonders what happened to those flying cars The Jetsons promised by the early 2000s.</p></div>
	
</span>

<br />
<br />

<div id="Darrell_Box" class="span-4">
<span style="margin-left: 0em;">
<%= image_tag "Darrell_pp2.jpg", :size=>"150x150"%></div>
<p style="font-size: 160%; line-height: 10%"><b>Darrell Jones</b>, <i>Chief Communications Officer</i></p>

<div id="Darrell_Text" style="text-align: justify;">
<p style="font-size: 115%" float: left;>Darrell, aka DJ3, is a sophomore philosophy, politics, & economics major at Pomona College. He
often makes a scene in the dining halls because of his unmistakable laugh - it sounds like a seal barking and leaves him incapacitated. He loves playing catch, eating granola, and watching poorly dubbed films. </p></div>
	
</span>

</div>